### PR TITLE
Ryan/ignored view types

### PR DESCRIPTION
**Pull request by ryansgot**
Many recycler views will have items of varying types. You may not want to have the same foreground/background and swiping behaviors for these views (as I found in my own project using this library).

### CODE REVIEW

**Comment by alexandre-lefranc-ezeeworld** [comment]
@nikhilpanju Thank you for this great library.
I think this pull request is very interesting and should be accepted.
It works perfectly in my application.

**Comment by ryansgot** [comment]
Thanks, @alexandre-lefranc-ezeeworld . I've wondered whether this project has been abandoned or not, as there is another pull request that appears to have been ignored. That would be sad because I think it's a great library that has been of good use to me. I'm considering hosting my own variant of this library, but I'd rather the owner, @nikhilpanju provide some feedback or pull my code in to the master branch and make a build--it's just less confusing that way.

**Comment by nikhilpanju** [comment]
@ryansgot @alexandre-lefranc-ezeeworld Hello. Thank you for your pull request. This library is not abandoned. I've planned some new features for future releases. I'm very busy with certain other projects for now and will get back to this asap.

As for your pull request, I'll be looking into it soon. Thank you for contributing!

**Comment by ryansgot** [comment]
@nikhilpanju No problem. I am happy to help. I like this library.

**Comment by ryansgot** [comment]
@nikhilpanju Are you going to do anything with this PR?

**Comment by nikhilpanju** [comment]
@ryansgot Merged, thank you. Will be available in the next release.

**Pull request merged**
